### ISSUE TITLE
播放直播有情况会出现这个问题

### ISSUE THREAD

**Issue by DancingSnowInFingertips** [Doikki/DKVideoPlayer#544]
2020-06-11 11:09:43.778 18945-18945/? E/ExoPlayer: internalError [eventTime=270.27, mediaPos=163.45, window=0, period=0, loadError]
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException: RTMP error: -3
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:222)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:49)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2020-06-11 11:09:49.681 18945-19420/? E/ExoPlayerImplInternal: Source error.
    net.butterflytv.rtmp_client.RtmpClient$RtmpIOException: RTMP error: -3
        at net.butterflytv.rtmp_client.RtmpClient.open(RtmpClient.java:222)
        at com.google.android.exoplayer2.ext.rtmp.RtmpDataSource.open(RtmpDataSource.java:49)
        at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
        at com.google.android.exoplayer2.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:956)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

![image](https://user-images.githubusercontent.com/32406771/84341559-03017680-abd6-11ea-92e4-d8f0904d3f60.png)

出现这个异常后播放器就卡顿在那不动弹了，看他样子貌似是说播放源有问题，可是如果我退出重新进还是这个直播地址就正常了

**Comment by DancingSnowInFingertips** [comment]
关键他也不走播放错误的回调，还没法进行处理

**Comment by DancingSnowInFingertips** [comment]
我后来加了个网络重连和超时监听，这个问题就彻底解决了，不知道如果在库里如果加上这些监听会不会更好

**Comment by 0toN** [comment]
换 ijk 模式就可以了
