### ISSUE TITLE
使用ExoPlayer经常会报这个异常

### ISSUE THREAD

**Issue by 743306400** [Doikki/DKVideoPlayer#568]
SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1531)
        at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1293)
        at com.dueeeke.videoplayer.exo.ExoMediaPlayer$2.run(ExoMediaPlayer.java:192)

我百度看了下说是应用程序中的某些代码正在错误的线程上访问SimpleExoPlayer实例,希望大佬看一下

**Comment by Doikki** [comment]
不用管
