### ISSUE TITLE
SimpleExoPlayer 子线程release报错警示，运行您的demo

### ISSUE THREAD

**Issue by MenShengSeLang** [Doikki/DKVideoPlayer#603]
new Thread() {
                @Override
                public void run() {
                    //异步释放，防止卡顿
                    player.release();
                }
            }.start();
错误是2020-11-30 16:30:00.516 18085-18458/com.dueeeke.dkplayer W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
    java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1531)
        at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1293)
        at com.dueeeke.videoplayer.exo.ExoMediaPlayer$2.run(ExoMediaPlayer.java:192)

**Comment by Doikki** [comment]
不用管，我故意而为
