### ISSUE TITLE
ExoMediaPlayer release illegalexception!

### ISSUE THREAD

**Issue by ShenYu0812** [Doikki/DKVideoPlayer#650]
DKVideoPlayer version: 3.2.6
```kotlin
    def DKPLAYER_VERSION = "3.2.6"
    // DKPlayer 默认使用MediaPlayer解码
    implementation "com.github.dueeeke.dkplayer:dkplayer-java:$DKPLAYER_VERSION"
    // DKPlayer exoPlayer解码
    implementation "com.github.dueeeke.dkplayer:player-exo:$DKPLAYER_VERSION"
    // DKPlayer 预加载库
    implementation "com.github.dueeeke.dkplayer:videocache:$DKPLAYER_VERSION"
```
common invoke  ```videoView.release()```

adb logcat:
```txt
W/SimpleExoPlayer: Player is accessed on the wrong thread. See https://exoplayer.dev/issues/player-accessed-on-wrong-thread
java.lang.IllegalStateException
        at com.google.android.exoplayer2.SimpleExoPlayer.verifyApplicationThread(SimpleExoPlayer.java:1531)
        at com.google.android.exoplayer2.SimpleExoPlayer.release(SimpleExoPlayer.java:1293)
        at com.dueeeke.videoplayer.exo.ExoMediaPlayer$2.run(ExoMediaPlayer.java:192)
```

error reason:
ExoPlayer ```release()``` method cannot invoke in work thread !(https://github.com/google/ExoPlayer/issues/5759)

error code(com.dueeeke.videoplayer.exo.ExoMediaPlayer#release)
```java
    @Override
    public void release() {
        new Thread() {
                @Override
                public void run() {
                    //异步释放，防止卡顿
                    player.release();
                }
            }.start();
    }
```

**Comment by Doikki** [comment]
3.3.0已经解决
