### ISSUE TITLE
播放 m3u8 失败

### ISSUE THREAD

**Issue by SuperZhouyong** [Doikki/DKVideoPlayer#721]
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/20082068/135838843-d2f2bcc8-3cf7-4bdf-aadc-6fa9268ace47.png">
2021-10-04 18:47:37.937 3423-3423/com.kk.xxx E/ExoPlayer: playerFailed [eventTime=10.81, mediaPos=8.26, window=0, period=0
      com.google.android.exoplayer2.ExoPlaybackException: Source error
        at com.google.android.exoplayer2.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:580)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:201)
        at android.os.HandlerThread.run(HandlerThread.java:65)
     Caused by: com.google.android.exoplayer2.ParserException: Cannot find sync byte. Most likely not a Transport Stream.
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.findEndOfFirstTsPacketInBuffer(TsExtractor.java:450)
        at com.google.android.exoplayer2.extractor.ts.TsExtractor.read(TsExtractor.java:317)
        at com.google.android.exoplayer2.source.hls.BundledHlsMediaChunkExtractor.read(BundledHlsMediaChunkExtractor.java:67)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.feedDataToExtractor(HlsMediaChunk.java:468)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.loadMedia(HlsMediaChunk.java:438)
        at com.google.android.exoplayer2.source.hls.HlsMediaChunk.load(HlsMediaChunk.java:394)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:417)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)

@Doikki 博主知道咋解决么

**Comment by SuperZhouyong** [comment]
https://cloud.tencent.com/developer/article/1819446 @Doikki 可以看看 这个里面的解决方案，能放到代码里面么

**Comment by SuperZhouyong** [comment]
https://github.com/google/ExoPlayer/commit/0697fb3955d8a30edb935cc428d515e2fd9d48cb

https://github.com/google/ExoPlayer/issues/3149

**Comment by aizyxaizyx** [comment]
你这边解决了吗，我也遇到了这个问题

**Comment by SuperZhouyong** [comment]
上面已经说解决方案了，https://cloud.tencent.com/developer/article/1819446
