### ISSUE TITLE
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.setLevel(int)' on a null object reference         at xyz.doikki.videocontroller.component.TitleView$BatteryReceiver.onReceive(TitleView.java:200)

### ISSUE THREAD

**Issue by Jack-bin183** [Doikki/DKVideoPlayer#731]
使用3.35版本
安卓10
报空指针

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.drawable.Drawable.setLevel(int)' on a null object reference
        at xyz.doikki.videocontroller.component.TitleView$BatteryReceiver.onReceive(TitleView.java:200)

**Comment by Jack-bin183** [comment]
// 基于IjkPlayer的视频播放器 https://gitee.com/tcy0206/dkplayer
    implementation 'xyz.doikki.android.dkplayer:dkplayer-java:3.3.5'
    // 可选，如需要缓存或者抖音预加载功能请引入此库
    implementation 'xyz.doikki.android.dkplayer:videocache:3.3.5'
    implementation 'xyz.doikki.android.dkplayer:player-exo:3.3.5'
    // 可选，包含StandardVideoController的实现
    implementation 'xyz.doikki.android.dkplayer:dkplayer-ui:3.3.5'
