### ISSUE TITLE
Md5FileNameGenerator异常

### ISSUE THREAD

**Issue by NewHuLe** [Doikki/DKVideoPlayer#741]
异常日志：
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.lastIndexOf(int)' on a null object reference
       at h.h.a.r.f.b(Md5FileNameGenerator.java:1)
       at h.h.a.r.f.a(Md5FileNameGenerator.java:1)
       at com.danikula.videocache.HttpProxyCacheServer.g(HttpProxyCacheServer.java:2)
       at h.d0.a.a.e.c.a.y1.o.o.a.d(PreloadManager.java:1)
       at h.d0.a.a.e.c.a.y1.o.o.a.a(PreloadManager.java:1)
不知道这个url的MD5为什么会出现这种问题，希望作者看到能够给出修复办法，目前线上问题增长很快，但是自己无法复现。

**Comment by Doikki** [comment]
播放地址是空的
