### ISSUE TITLE
divide by zero

### ISSUE THREAD

**Issue by miantiaox** [Doikki/DKVideoPlayer#756]
``` 崩溃信息:
divide by zero

类名:u5.j$a

方法:onPlayStateChanged

行数:94

类型:java.lang.ArithmeticException

时间:2022-04-08_22:26

设备名称:KB2000

设备厂商:OnePlus

系统版本:Android 11-30

CPU-ABI:arm64-v8a

versionCode:103

versionName:1.103

全部信息:
java.lang.ArithmeticException: divide by zero
	at u5.j$a.onPlayStateChanged(Unknown Source:94)
	at xyz.doikki.videoplayer.player.VideoView.setPlayState(Unknown Source:35)
	at xyz.doikki.videoplayer.player.VideoView.onInfo(Unknown Source:31)
	at xyz.doikki.videoplayer.exo.ExoMediaPlayer.onPlaybackStateChanged(Unknown Source:18)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$updatePlaybackInfo$16(Unknown Source:2)
	at com.google.android.exoplayer2.ExoPlayerImpl.r(Unknown Source:0)
	at a1.i.invoke(Unknown Source:42)
	at com.google.android.exoplayer2.util.ListenerSet$ListenerHolder.invoke(Unknown Source:17)
	at com.google.android.exoplayer2.util.ListenerSet.lambda$queueEvent$0(Unknown Source:16)
	at com.google.android.exoplayer2.util.ListenerSet.a(Unknown Source:0)
	at m.f.run(:6)
	at com.google.android.exoplayer2.util.ListenerSet.flushEvents(Unknown Source:66)
	at com.google.android.exoplayer2.ExoPlayerImpl.updatePlaybackInfo(Unknown Source:429)
	at com.google.android.exoplayer2.ExoPlayerImpl.handlePlaybackInfo(Unknown Source:206)
	at com.google.android.exoplayer2.ExoPlayerImpl.lambda$new$1(Unknown Source:0)
	at com.google.android.exoplayer2.ExoPlayerImpl.s(Unknown Source:0)
	at h.a.run(:16)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:8030)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)

```

**Comment by miantiaox** [comment]
已排查到问题，获取视频宽高为0导致，故关闭issue
